# QA Profile
spring.datasource.url=jdbc:mysql://localhost:3306/hotel_db_qa
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
logging.level.com.example.hotelmanagementsystem=INFO
server.port=8081

